### ISSUE TITLE
ansi_logs enables colors unconditionally, even if output is not a terminal

### ISSUE THREAD

**Issue by flokli** [EmbarkStudios/tracing-logfmt#15]
**Describe the bug**
I'd like to use `tracing-logfmt` to log both to CLI, if run interactively, as well as to the systemd journal, if run as a systemd service.

I'd have expected the colorful output to be a user convenience thing, and only happen if the output is a (user-facing) terminal, not if it's running as a service, or piped to somewhere else. Doing colorful logfmt output "breaks parsing", as in that `level=info` becomes `\u001b[1;38;2;109;139;140mlevel\u001b[0m=\u001b[1;32minfo\u001b[0m `, which can't be matched that easy in queries.

**To Reproduce**
1. Enable tracing-logfmt as described in your application
2. Run it as a CLI output, see pretty colors
3. Run it as a systemd service (for example via `systemd-run`), or simply redirect the log output to another CLI. Observe there's colors too in the output.

**Expected behavior**
I'd expect color formatting to only happen if the output is a terminal.

**Comment by fredr** [comment]
The ansi feature was only added as a debugfeature meant to be used in local development. But it makes sense to be able to disable it when the feature is enabled.

Added a PR that adds support for toggling it, with the default to be enabled when stdout is a terminal
